################################################################################################
# Deleting an Entire VPC Environment in AWS                                                    #
#                                                                                              #
# By Robert J. Calva - Red Hat LATAM - 2019                                                    #
#                                                                                              #
# NOTE: just set the aws_region, aws_zone, name_zone, attendee, aws_keypair and                #
# volume_type variables as you wish!                                                           #
#                                                                                              #
# IMPORTANT: regarding storage_type information, please take a look at this link:              #
# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html                       #
#                                                                                              #
# Variable examples:                                                                           #
#                                                                                              #
# aws_region could be: sa-east-1 or us-east-1                                                  #
# aws_zone could be: sa-east-1a, sa-east-1b, us-east-1a, us-east-1b                            #
# name_zone could be: example.com                                                              #
# volume_type could be: standard or gp2                                                        #
#                                                                                              #
# Enjoy!                                                                                       #
################################################################################################
- name: Delete an Entire VPC Environment in AWS
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Getting EC2 Instance Info {{ instance_name }}
    ec2_instance_info:
      filters:
        "tag:Name": "{{ instance_name }}"
        instance-state-name: running
      region: "{{ aws_region }}"
    register: ec2
      
  - name: Deleting an AWS Instance {{ instance_name }}
    ec2:
      instance_ids: "{{ ec2.instances[0].instance_id }}"
      region: "{{ aws_region }}"
      wait: yes
      wait_timeout: 500
      state: absent
    ignore_errors: yes
      
  - name: Gather information about VPC {{ attendee }}
    ec2_vpc_net_info:
     region: "{{ aws_region }}"
     filters:
       "tag:Name": "VPC {{ attendee }}"
    register: vpc
    
  - name: Gather information about Route Tables for VPC {{ attendee }}
    ec2_vpc_route_table_info:
      region: "{{ aws_region }}"
      filters:
        "tag:Name": "VPC {{ attendee }}"
    register: rtb
      
  - name: Delete VPC Public Subnet Route Table for VPC {{ attendee }}
    ec2_vpc_route_table:
      region: "{{ aws_region }}"
      route_table_id: "{{ item.id }}"
      vpc_id: "{{ vpc.vpcs[0].id }}"
      state: absent
    loop: "{{ rtb.route_tables }}"
   
  - name: Delete VPC Internet Gateway for VPC {{ attendee }}
    ec2_vpc_igw:
      region: "{{ aws_region }}"
      vpc_id: "{{ vpc.vpcs[0].id }}"
      tags:
        Name: "VPC {{ attendee }}"
      state: absent
   
  - name: Delete Subnet for VPC {{ attendee }}
    ec2_vpc_subnet:
      region: "{{ aws_region }}"
      vpc_id: "{{ vpc.vpcs[0].id }}"
      tags:
        Name: "VPC {{ attendee }}"
      state: absent

  - name: Delete an AWS Security Group for our Workshop
    ec2_group:
      name: "aws-workshop-sec-group"
      vpc_id: "{{ vpc.vpcs[0].id }}"
      region: "{{ aws_region }}"
      tags:
        Name: "VPC {{ attendee }}"
      state: absent
        
  - name: Deleting the VPC {{ attendee }} in AWS {{ aws_region }}
    ec2_vpc_net:
      name: "VPC {{ attendee }}"
      tags:
        Name: "VPC {{ attendee }}"
      purge_cidrs: yes
      region: "{{ aws_region }}"
      state: absent


